# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:pcl2V49VTg7Hcr1MRXPDEawVzdNGzzKBOprrsenwHJWvG+nQJx95j7HlyETvtesjbc1Efuw6fSBzxRYG50AiCMeySPWavnHTJ59rDifqH9wHK45GOG2LJCChMLU+FoAXnIjib7KahO2FDvUKc1BjQM/CRbrIn4M7Lzv/2NPbd8PzV9DVFUfda2LoO/4bFLr/3nCvBfgpJh+aC3zK3JxutMAgA4wQTUMKZCqcxbTUbw==,iv:w83Drz5pGb82wd+Y7DljOb0bkoroxYUv2MolwOEQyfI=,tag:hsEzQndcWhOrwTLWnDR8HQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1exgmxvupx9zflu7w8n4t5vkmyshq0n47j7jf0dcapc2gux2lqcrqwrrjdf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS3Npd3piN1RXNnVZY29o
        NjY4aW0xeDl2SW12aWhERytoWVBPOWJuNmh3ClRkaVFyWWtqYlR2d0E5NHNaUU11
        UUNjOURLSTZTeTUvMmJqc1BqK3VHV0UKLS0tIERJZFdEUzVkMFhYTG5CbnRwVzZL
        ZEkvZ2VTSlMyNmxQelFCbFgyVm04UEUKZjdbUDAB8SSRMOEDtBAw4ePqkgzpUUtu
        guLGlvaCxlqh5ZAcOH0aazDfe8hGTj7i+f0qod4J4JXQ6CFj2tU3XQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T13:34:09Z"
  mac: ENC[AES256_GCM,data:2H9wkuN1CGCMM/mN9yHo2AQhXmdlQltY95BYPweBjNhqBCrrTbXca1O5fDkqAbwpc3WtuaXkMCtBI6xxjtE+rMbE5c4d5/onp3YyzUuARx+UjhOzmz3tn8bLJeDdkoNdARc60yroIvTzHPjFLgajOZxso1RsxMihYu0JODiMFTI=,iv:FzINfBGu0yyGK9hZXOC4V0It9HQj5JzE/F6Q4s3+AUc=,tag:H3VrUUPi9Kil3SgZgCkoww==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
