apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
  - name: debug
    image: ubuntu:latest
    command: ["bash", "-c", "sleep 3600"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-root
      mountPath: /host
    - name: host-dev
      mountPath: /host/dev
  volumes:
  - name: host-root
    hostPath:
      path: /
  - name: host-dev
    hostPath:
      path: /dev
  restartPolicy: Never