# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:lEcaWkszeitLAstpbtuz8f7bJqHoQepOrMx5smUg6n8=,iv:FYNSyK7cxzGnXBUGvEjj2zInw1OYFxzYMhEGOn7Hpo0=,tag:YMe1GONQWudDAElYANzuMQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1exgmxvupx9zflu7w8n4t5vkmyshq0n47j7jf0dcapc2gux2lqcrqwrrjdf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK2dnc2dHU0k5UG00b1FS
        bTVYbFVsOFVkb3BWamZLbVJpd2hzYXJCK0g0Ck5rMWw1SGNidmUyUWxVcUtOL1ov
        WWJ2Q0VYUFM1OU5BdFpFR25yYWt6MmsKLS0tIDNabWU3RHlyQnNtYmh5eDJuaXgv
        S0N0SGlWWmJINGx3NFQwbVplN0dPWjQKAWW0sbdqhCtYLrUo1DnnN3gF+4tfCS3J
        RKA5QXNQnv/Ohd295l8zg935aY+Sob0H3/jGishU3lGrO1obT+KX9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T22:38:17Z"
  mac: ENC[AES256_GCM,data:umOEtqe9uivczhbOVH4ENpM4ONkRk92bLdxIyt7KKnuuI9mrs/8p24iKBLzvsRpU7b0gRAKKKjL93Nu8lng0A1/P8H9XI58np+OjHBXQhJ6vSGiGkQQePaGp6HtDSm0HXOIZKX1k4m5uZjaQTPh6+LuxYhO9xRbOMAa3MtjbN+g=,iv:I+ClT48LLJxlU2U+qIeVB04yAL3zMSsalFpD5IRRZk8=,tag:IneDp3viSStNP5HWbV40VQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
