# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:NdnFaMmC+lmMqdPdr1bjSIR0sv1W2Bhofy55VDh/UNk=,iv:snaUmx7pF2FF8LFw3VApzTXNK7+dpcdCyALS0uWrW3U=,tag:YY8swujaMAz8ufF4rAAsLA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1exgmxvupx9zflu7w8n4t5vkmyshq0n47j7jf0dcapc2gux2lqcrqwrrjdf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQng4ajRINU1YZ2I4aVVW
        WEpjSnl1S215THoxaXVWN2VkNWZnMXFtYXo4CjhhREIrd1A3VmJIblVYREZTbWEy
        cW83YVFNZFE4RnJaa21USUhNL0w2dEkKLS0tIFh3ZHljeUxhN2tDV3FwK2ZFVWhT
        ODlOaFhUMlBFVnZBSTd0UDZxa3NWZzQK+JLNzhoZ52cNhletrwxoBOsDwjSZ6Io6
        Co4tcLlwmycACZd9fiX6W7XRUP/yF/ePdTgteECgi0WfN6Bl0aHPHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T13:34:09Z"
  mac: ENC[AES256_GCM,data:OXNpC99s8Fez8BIJHNDK5ST7kU5EivXugmIOVKg50nyF+ovV61Kc9fnuLozS0NZ4f5hc0IPYZVUbfNwJ7u0kICDnlFzh5iPSiZijLifJ1K8OVNOyv/Tv878H0QRwEfIX83MYxCNTe0878H35HPulhc9TnJY1qZVUJFQ7KCslBTU=,iv:ZI5Ir4n4nx00fXw+cUwXOh0l5b6cxyf7TcrO78AX4GQ=,tag:w23vCP2Yml+L+4XevDcTxQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
