apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:o1uZMqgIgyW6p30Z,iv:CAxPqZIV3mHg63Di05nnJuO2AsGZmclaT1NAe6+maXA=,tag:aXSr7iiY48hfIpD6R+KTzA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1exgmxvupx9zflu7w8n4t5vkmyshq0n47j7jf0dcapc2gux2lqcrqwrrjdf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMnU0eVpjWktsRkI3RzNh
        SW9oa2pHbTZTVnJ6ajAxK21RaGVpV1VxNWkwCkZCZExORG9QbmJMallpMnZ2eDd4
        aUtOVzc0RkVBRmFucEJERTFQeDZaSzAKLS0tIEE2cldKYlNBSWZzTHRmbHZJMDVH
        Z3lRakRSbGpNZ3VJUDdOcHdYT2VFVlEKwOLvwLnZIsU8fnx+lvBoCPS5QM1Vku1p
        HiTwEhvqN+ADMIOaV7M9TnZZBeWpCXsgd9olWlPFa7y8d5rN2Fg2Ow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T21:08:50Z"
  mac: ENC[AES256_GCM,data:f+lI15MO8ApEmqNv7XGRWp9OxYVRX1YwS++QUXarQ0x0EE4r1msdV52m+mJCIy90IJbyQ/ywUy3iKS5UrRHNzW04WknVCsbTbEGCR8w65vbRft/4yoTvW9KBUqZ+ixsa49ut1vwa/jPM2oEU/yz0kbuE6W5JSX+jz1nw3tnIAKg=,iv:55nOIRGtnfn1hhYt5LyhyLVQ2jBvrfqJ2XJnVa8wwtk=,tag:/KNx2IYq8Dn2ABhX9sYkug==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
